Update django and python, add github action
hearsaycorp/django-livefield pull request #62
Opened 2023-12-12 14:54 UTC by csizmaziakiki

2023-12-12 16:14 UTC, lopezm1 approved these changes

2023-12-12 16:15 UTC, lopezm1 requested changes

2023-12-12 16:15 UTC, lopezm1 commented on setup.py
> +    version='3.4.0',
Can we bump this to 4.0.0?

2023-12-12 17:25 UTC, lopezm1 approved these changes

2023-12-12 17:59 UTC, rbm commented
Nice. You can close #58 from the community after this as well.

If you're in here, might be worth adding Python 3.12 and Django 5.0 to the test matrix as well since they are out now and there's some OSS usage of this library where folks might be on more cutting edge, non-LTS versions of Py/Django.

2023-12-12 20:27 UTC, dbenzel approved these changes

2023-12-13 09:15 UTC, csizmaziakiki commented
> Nice. You can close #58 from the community after this as well.
> 
> If you're in here, might be worth adding Python 3.12 and Django 5.0 to the test matrix as well since they are out now and there's some OSS usage of this library where folks might be on more cutting edge, non-LTS versions of Py/Django.

Thank you for the input! I would like to get this merged ASAP and don't want to make the reviews stale since I have a dependency on this package that I need to update, but I'll make the updates in a following PR

2023-12-13 09:16 UTC, merged